### ISSUE TITLE
stx.tab_bar() returns id as str instead of int

### ISSUE THREAD

**Issue by rymdluo** [Mohamed-512/Extra-Streamlit-Components#1]
`tab_bar_id = int(stx.tab_bar(data=tab_bars, default=1)) # Returns a str so we cast to int`

I noticed that after the first selection, the tab_bar returns the id as a str, casting it resolves the issue but I thought to flag it so that it can be more consistent.

**Comment by Mohamed-512** [comment]
Since this might not suite all developers, who need different data type to the IDs, I chose to keep it a string. Will add a parameter to internally parse the return type, to whatever is supplied.

**Comment by Mohamed-512** [comment]
Introduced in 0.1.42
