### ISSUE TITLE
Do cookies work on streamlit share?

### ISSUE THREAD

**Issue by LeoGrin** [Mohamed-512/Extra-Streamlit-Components#12]
Hi!
Do you know if this package's cookies are supposed to work when an app is deployed with streamlit share? It works fine on local, but setting cookies doesn't seem to work when deployed.
Thanks!

**Comment by LeoGrin** [comment]
It works when deployed on Heroku! (Haven't tried on Streamlit Share again since last comment).

**Comment by mrtj** [comment]
Well, I do not know if they effectively disabled cookies on share.streamlit.io but it would perfectly make sense. As cookies stored on domain level (in this case on share.streamlit.io), there would be just one global cookie store shared by all published applications. So if a single user run two different app published on share.streamlit.io, the second app would have access also to the cookies of the first app, potentially including sensitive information (authentication token, for example). This would be certainly disastrous from a security point of view.

**Comment by Mohamed-512** [comment]
Thanks @mrtj for your comment, that makes very much sense! Will include that note in the README file.
