### ISSUE TITLE
cookie get on version 0.1.51 is not working on streamlit 1.1.0

### ISSUE THREAD

**Issue by vvvlad** [Mohamed-512/Extra-Streamlit-Components#13]
Using the example from the main page for cookies, 
the cookie is created, but get always return None.
Tested on Chrome and Edge.

**Comment by cfoisy-osisoft** [comment]
I confirm the behavior reported by @vvvlad

**Comment by Mohamed-512** [comment]
Issue fixed on 0.1.52

**Comment by vvvlad** [comment]
confirm issue fixed, thank you!
