### ISSUE TITLE
Compatibility with share.streamlit.io

### ISSUE THREAD

**Issue by Sentaku67** [Mohamed-512/Extra-Streamlit-Components#15]
Hi Mohamed, Thank you for your great effort on this amazing library,
I have one question about if it still works on the latest version of streamlit==1.2.0 or if there is some additional steps to do for this purpose?

**Comment by Mohamed-512** [comment]
Hi @Sentaku67, sorry for the late reply. It works just fine on Streamlit Share but please bear in mind some security notes that's mentioned in the Cookie Manager's section in the project's README.md file
