### ISSUE TITLE
Cookie Manager only working for Firefox?

### ISSUE THREAD

**Issue by t-kalisch** [Mohamed-512/Extra-Streamlit-Components#19]
Hello Mohamed,

I'm fairly new to Streamlit and found your Cookie Manager which is pretty straight-forward to use and perfect for a new-comer like me, thanks a lot for this! However, it only seems to actually save cookies on Firefox. Is this a known problem and is there a way around this, to make it browser-independent?

Best,
Tim

**Comment by Mohamed-512** [comment]
Hi @t-kalisch ,

Welcome to Streamlit! And glad to know you are using CookieManager.
Unfortunately, cookies are browser specific. Matter of fact, if you set a cookie on Chrome and a specific user and then switched to another Google account, or opened incognito, you will not find that cookie.

Something good to know -even though I doubt you might need it-, some corporates make software to manage apps on employees computers such that they are automatically redirected to corporate sites without signing in, as they use something called SSO (Single Sign On) which leverages the current logged in user on the computer's details and logs the user in automatically in some site.

Good Luck.

**Comment by Mohamed-512** [comment]
I should work in any browser just fine. I personally tried it Chrome, Edge & Safari. So I don't know why you are facing difficulties.
