### ISSUE TITLE
Ability to add html/css styles via parameters

### ISSUE THREAD

**Issue by rymdluo** [Mohamed-512/Extra-Streamlit-Components#2]
Since extra streamlit components uses its own html and embeds it into streamlit, theming is not directly possible. It would be handy if there was some way to inject html code to override some of the styling.

For example:

```
tab_bar_styles= """
    <style>
    .menu-item {
        padding: 0px 10px !important;
    }
    </style>
    """
stx.tab_bar(data=[
    stx.TabBarItemData(id=1, title="ToDo", description="Tasks to take care of"),
    stx.TabBarItemData(id=2, title="Done", description="Tasks taken care of"),
    stx.TabBarItemData(id=3, title="Overdue", description="Tasks missed out"),
], default=1, custom_html=tab_bar_styles)
```

The custom_html just needs to be passed into frontend/index.html of the component, after the bootstrap stylesheet.

**Comment by Mohamed-512** [comment]
Closed as this feature request is not the near future scope of this package.
