### ISSUE TITLE
Cookies as a server (get all including defined externally)

### ISSUE THREAD

**Issue by miannini** [Mohamed-512/Extra-Streamlit-Components#20]
I was looking into a way to get all cookies, even those defined externally such as web_auth in a login page.
I think that there is a solution in the universal-cookie package:

https://www.npmjs.com/package/universal-cookie

Server Example:
const cookies = new Cookies(req.headers.cookie);

so could be possible to have an additional version for server?

at this moment I see only this option available in extra_streamlit_components/CookieManager/frontend/src/CookieManager.jsx:
const cookies = new Cookies()

**Comment by Mohamed-512** [comment]
The package doesn't have server support as the CookieManager is a frontend component which communicates back to the server. Not the other way around.
