### ISSUE TITLE
suggestion for stx.stepper_bar

### ISSUE THREAD

**Issue by littlepanda0716** [Mohamed-512/Extra-Streamlit-Components#23]
Thanks for the great components package! I’m now trying to use stepper_bar in my project, and the present logic to use it is to click the button near the chosen one, is there any way that i can use it even when i want to choose the last one or any one else when the first selection is chosen?

**Comment by Mohamed-512** [comment]
The idea of the stepper bar to be sequential. However, I just created a [version 01.54](https://pypi.org/project/extra-streamlit-components/) to add an option to not make stepping require sequence.
