### ISSUE TITLE
CookieManager.set(expires_at=) default value issue

### ISSUE THREAD

**Issue by yenpinchiu** [Mohamed-512/Extra-Streamlit-Components#24]
Hi, thanks for your nice Streamlit add-ons.
When I use the cookie manager component, I find an issue.

https://github.com/Mohamed-512/Extra-Streamlit-Components/blob/596d088a30806a5273a0ae97b11de08a3e26c683/extra_streamlit_components/CookieManager/__init__.py#L24

Based on the Python behavior, the default value of expires_at will always be the Steamlit app started time but not the function called time, which means one day after the Steamlit app started, I won't be able to set the cookie without giving the expires_at because the default expires_at time will be earlier than the current time.

I'm not sure it's an intentionally designed mechanism or a bug.
Thank you.

**Comment by Mohamed-512** [comment]
It's a bug, great catch! You can update to [version 0.1.55](https://pypi.org/project/extra-streamlit-components/0.1.55/
) for the fix.
