### ISSUE TITLE
Cookie Manager errors instead of returning a default

### ISSUE THREAD

**Issue by kevinlinxc** [Mohamed-512/Extra-Streamlit-Components#3]
When I instantiate cookie manage and try to get a token, for a quick flash (1/4 second), I see streamlit output the error
`'NoneType' object has no attribute "get"`, referring to cookie_manager.get(). Is this because instantiating takes a second, or what?

**Comment by kevinlinxc** [comment]
Actually, it is not cookie_manager.get() but this line: https://github.com/Mohamed-512/Extra-Streamlit-Components/blob/master/extra_streamlit_components/CookieManager/__init__.py#L32

that is raising the error. I believe it is because I'm trying to get a cookie that doesn't exist. I expected it to return None, but instead it raises this error. 

My use case is that I'm using OAuth to authenticate, and I want to store the refresh_token in cookies so that users don't have to authenticate every time they refresh. So, I have to check if the cookie exists and use it if it does, or generate a new token if it doesn't exist. It seems like there isn't a way to check if the cookie exists though, using functions from this package.

**Comment by kevinlinxc** [comment]
Here is my suggestion:


```
-    def get(self, cookie: str, key: any = 0) -> any:
+    def get(self, cookie: str, key: any = 0, default=None) -> any:
         if self.use_streamlit_state and st.session_state.cookies is not None:
             return st.session_state.cookies.get(cookie)
+        if self.cookies is None or key not in self.cookies:
+            return default
         return self.cookies.get(cookie)
```

**Comment by Mohamed-512** [comment]
This might be because you are on a Streamlit version < 0.86. Will try to fix it anyways, but I encourage you to still update Streamlit.

**Comment by Mohamed-512** [comment]
Fixed on 0.1.42

**Comment by kevinlinxc** [comment]
No, I was on Streamlit version 0.88

**Comment by Mohamed-512** [comment]
That was weird. Should be fine now though.

**Comment by LeoGrin** [comment]
I have the same issue on Streamlit 0.89 and Extra-Streamlit-Components 0.1.44.

## Minimal code:

```
import streamlit as st
import extra_streamlit_components as stx
import time

cookie_manager = stx.CookieManager()
#time.sleep(3)
print(1)
print(cookie_manager.get_all())

user_id = cookie_manager.get("userID")

if not user_id:
    print("here")
    user_id = 1000
    cookie_manager.set("userID", user_id)

print(2)
print(cookie_manager.get_all())
```

## Logs:

### Minimal example

```
1
None
here
2021-10-04 10:34:27.454 Traceback (most recent call last):
  File "/Users/leo/opt/anaconda3/envs/nootropics/lib/python3.8/site-packages/streamlit/script_runner.py", line 354, in _run_script
    exec(code, module.__dict__)
  File "/Users/leo/JupyterProjects/nootropics_survey/bug_minimal_example.py", line 15, in <module>
    cookie_manager.set("userID", user_id)
  File "/Users/leo/opt/anaconda3/envs/nootropics/lib/python3.8/site-packages/extra_streamlit_components/CookieManager/__init__.py", line 47, in set
    st.session_state.cookies.update({cookie: val})
AttributeError: 'NoneType' object has no attribute 'update'

1
{'_xsrf': '2|8db201b7|2a028b67716bb5dfb39e199d1853d838|1633336469'}
here
2
{'_xsrf': '2|8db201b7|2a028b67716bb5dfb39e199d1853d838|1633336469', 'userID': 1000}
1
{'_xsrf': '2|8db201b7|2a028b67716bb5dfb39e199d1853d838|1633336469', 'userID': 1000}
2
{'_xsrf': '2|8db201b7|2a028b67716bb5dfb39e199d1853d838|1633336469', 'userID': 1000}
```

### Minimal example with time.sleep(3) uncommented

```
1
1
{'_xsrf': '2|bdcdc714|ada4277c00698fa7994148e01c240dc5|1633336740'}
here
2
{'_xsrf': '2|bdcdc714|ada4277c00698fa7994148e01c240dc5|1633336740', 'userID': 1000}
1
{'_xsrf': '2|bdcdc714|ada4277c00698fa7994148e01c240dc5|1633336740', 'userID': 1000}
2
{'_xsrf': '2|bdcdc714|ada4277c00698fa7994148e01c240dc5|1633336740', 'userID': 1000}
```

I'm not sure why there are two "1" at the beginning, but it works with the time.sleep.

I'm not sure if this is related, but if I stop the app and relaunch (again with time.sleep uncommented), I get exactly the same log, which means that the cookie userID isn't read (though it appears to be saved if I check). The example you provide here https://github.com/Mohamed-512/Extra-Streamlit-Components works for me though.
