### ISSUE TITLE
Cookies aren't set with SameSite: Strict

### ISSUE THREAD

**Issue by blipk** [Mohamed-512/Extra-Streamlit-Components#32]
They are also not "Secure":
![Screenshot from 2022-10-01 13-02-50](https://user-images.githubusercontent.com/45532845/193384011-37cdf9a5-901f-47b6-9b11-be0fe4928e7a.png)

Using this code:
```Python
self.cookie_manager = stx.CookieManager()
cookie_expiry_time = datetime.now(tz=pytz.timezone(self.user_tz)) + timedelta(seconds=self.cookie_expiry_seconds)
self.cookie_manager.set("login_cookie", self.token, expires_at=cookie_expiry_time)
```

Same with locally hosted or on streamlit cloud.

**Comment by blipk** [comment]
The issue was in the `setCookie` function in CookieManager.jsx.

`samesite: "strict",` should be `sameSite: "strict",`

Looks like this isn't maintained, so I'm not going to bother with a PR for just that change, have fixed it myself with a fork, and so can anyone else if they read this.

**Comment by Mohamed-512** [comment]
Thanks @blipk for identifying a fix. It would have been great making a PR for it, and I will make sure to approve it and make a new version of the package including it.
