### ISSUE TITLE
Does the Cookie Manager accept Dicts at all?

### ISSUE THREAD

**Issue by mansidak** [Mohamed-512/Extra-Streamlit-Components#39]
Pretty much the heading. I'm attempting to add a dict as a cookie ( instead of a string, as shown in the gif) and it just doesn't get added :/

**Comment by Socvest** [comment]
Yes it does. Try this:

```
import json
val = json.dumps({'name':'Jacob'})

cookie_manager = CookieManager()
cookie_manager.set("cookieName", val)

# refresh browser
cookie_read = cookie_manager.get("cookieName") # will get json object
st.write(cookie_read)

```

Refresh browser and check

**Comment by Mohamed-512** [comment]
only primitive types can be added, as the web as we know it was built to accept cookies as strings. you can stringify the dict as suggested by @Socvest
