### ISSUE TITLE
Cookie Manager only works with buttons

### ISSUE THREAD

**Issue by kevinlinxc** [Mohamed-512/Extra-Streamlit-Components#4]
There seems to be timing issues when the cookie manager is used directly rather than with a button.

I've added one line to the example, `cookie_manager.set("test_cookie", "test_value")`, which should be compliant since it passes two strings, but when I try to run it I temporarily get an error and it doesn't set the cookie. Meanwhile, the button cookie setting works as expected, and I think this might be because of the slight delay that clicking creates, or maybe because the site updates when a button is pressed.

```
import streamlit as st
import extra_streamlit_components as stx

cookie_manager = stx.CookieManager()

st.subheader("All Cookies:")
cookies = cookie_manager.get_all()
st.write(cookies)

## important line here
cookie_manager.set("test_cookie", "test_value")

c1, c2, c3 = st.columns(3)
with c1:
  st.subheader("Get Cookie:")
  cookie = st.text_input("Cookie", key="0")
  clicked = st.button("Get")
  if clicked:
      value = cookie_manager.get(cookie)
      st.write(value)
with c2:
  st.subheader("Set Cookie:")
  cookie = st.text_input("Cookie", key="1")
  val = st.text_input("Value")
  if st.button("Add"):
      cookie_manager.set(cookie, val)
with c3:
  st.subheader("Delete Cookie:")
  cookie = st.text_input("Cookie", key="2")
  if st.button("Delete"):
      cookie_manager.delete(cookie)
```

**Comment by Mohamed-512** [comment]
It's not oly with buttons but when Streamlit renders its first view. You see that CookieManager is built on a React based cookie library, this is still treated by Streamlit as a component to be rendered (even though there's nothing to render out). Initially Streamlit renders an empty page and sequentially adds the component in your script line by line, during this phase and for this particular example, the Cookie Manager didn't actually initialise yet, making it impossible to add, remove, read cookies. To prove it try printing all cookies without a click of a button, you will notice it will return `None` and then corrects itself once Streamlit fully runs the script. One way to overcome the problem you are facing is to check if the cookies returned from `cookie_manager.get_all()` resemble an actual dictionary not `None`, then you can proceed with adding the cookie value you want. Hope this helps!

**Comment by kevinlinxc** [comment]
I understand what you've written, but I'm a bit unclear on how to proceed. Is there a sequence of steps that will guarantee that I can add to the dictionary directly using `cookie_manager.set("test_cookie", "test_value")`? As in, when is it guaranteed that cookie_manager.get_all() is a dictionary and not None?

**Comment by Mohamed-512** [comment]
Yes it needs to return be a dictionary first, i.e. the manager is initialized.
So an if statement would do the job, I could have just this check while setting the cookie, but other developers might need to know whether this operation was done successfully or not by looking if it returns an error or proceeds flawlessly.

**Comment by kevinlinxc** [comment]
This is not ideal, because sometimes the rerun in which it has OAuth information is not the run in which the dictionary from cookies is valid, so they don't coincide and it gets blocked. Ideally the cookie manager would be agnostic to timing, like session_state.

**Comment by Mohamed-512** [comment]
Ideally yes but this library is bounded by the limitations of the framework it's built for. Fow now I have no module built-in fix as I transparency to the developrs is important so they need to know whether the token was added or not. I would appreciate it if you open pull request for a potential fix, but until then I guess the way to go is through skipping the first run.
