### ISSUE TITLE
Recommended use of new cache features in regards to CookieManager

### ISSUE THREAD

**Issue by ksdaftari** [Mohamed-512/Extra-Streamlit-Components#40]
what is recommended change for 1.18+ of streamlit for below code snippet (given st.cache is now deprecated)? 

```
@st.cache(allow_output_mutation=True)
def get_manager():
    return stx.CookieManager()
```

**Comment by ksdaftari** [comment]
I am getting below warning if just used the code snippet from readme switching `st.cache_resource`

```
CachedStFunctionWarning: Your script uses st.component_instance() to write to your Streamlit app from within some cached code at get_manager(). This code will only be called when we detect a cache "miss", which can lead to unexpected results.

How to fix this:

Move the st.component_instance() call outside get_manager().
Or, if you know what you're doing, use @st.cache_resource(suppress_st_warning=True) to suppress the warning.
Traceback:
File "C:\Program Files\Python39\lib\threading.py", line 912, in _bootstrap
    self._bootstrap_inner()
File "C:\Program Files\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
File "C:\Program Files\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
File "C:\Users\kdaftari\Code\barepos\dashboards\cookie_dash.py", line 11, in <module>
    cookie_manager = get_manager()
File "C:\Users\kdaftari\Code\barepos\dashboards\cookie_dash.py", line 9, in get_manager
    return stx.CookieManager()
File "C:\Users\kdaftari\Code\barepos\venv\lib\site-packages\extra_streamlit_components\CookieManager\__init__.py", line 19, in __init__
    self.cookies = self.cookie_manager(method="getAll", key=key, default={})
```

**Comment by VovaViliLox** [comment]
Neither cache_data nor cache_resources have a flag that allows output mutation, so I am confused as well.

**Comment by aht** [comment]
+1 Currently Streamlit shows a deprecation warning but neither `cache_data` nor `cache_resource` can be used.

**Comment by moonbug-car** [comment]
+1 it is unusable in streamlit 1.18+

**Comment by callzhang** [comment]
+1 need a way to use st.cached_data

**Comment by Mohamed-512** [comment]
New package version uses `st.cache_resource`

**Comment by WillReynolds5** [comment]
+1

**Comment by hoorelbeke-jimmy** [comment]
I still have the same issue with the following snippet:

```python
import extra_streamlit_components as stx
import streamlit as st


@st.cache_resource
def get_manager():
    return stx.CookieManager()


cookie_manager = get_manager()
```

and following versions:

```bash
$ pip list | grep streamlit
extra-streamlit-components            0.1.60
streamlit                             1.29.0
```

**Comment by felimuno** [comment]
same issue streamlit 1.31.1

**Comment by thiamfook** [comment]
Same issue 
streamlit 1.32.0
extra-streamlit-components 0.1.71

My temporary workaround:
```
@st.cache_resource(experimental_allow_widgets=True) 
def get_manager():
    return stx.CookieManager()
```

**Comment by pinkponk** [comment]
extra-streamlit-components 0.1.71
streamlit                  1.37.1

Get this warning when running with @thiamfook fix. I have newer streamlit version than him.

`The experimental_allow_widgets parameter is deprecated and will be removed in a future release. Please remove the experimental_allow_widgets parameter from the @st.cache_resource decorator and move all widget commands outside of cached functions.

To speed up your app, we recommend moving your widgets into fragments. Find out more about fragments in [our docs](https://docs.streamlit.io/develop/api-reference/execution-flow/st.fragment).

If you have a specific use-case that requires the experimental_allow_widgets functionality, please tell us via an [issue on Github](https://github.com/streamlit/streamlit/issues).`

How should one use the cookie manager?

**Comment by jsensarma** [comment]
would love to understand how to get rid of the warning mentioned by @pinkponk above.

**Comment by jsensarma** [comment]
found a solution - add this before the app runs to suppress the warning in the UI

st.set_option('client.showErrorDetails', False)
