### ISSUE TITLE
Cookie lifetime

### ISSUE THREAD

**Issue by Anvasi1977** [Mohamed-512/Extra-Streamlit-Components#52]
Hi!
Do I understand correctly that you have removed the ability to set the lifetime of cookies?

**Version 0.1.56:**
`cookie_manager.set(cookie, val, expires_at=datetime.datetime(year=2022, month=2, day=2))`

**Version 0.1.60:**
`cookie_manager.set(cookie, val) # Expires in a day by default`

- Why was this done in version 0.1.60?
- Is there a way (in version 0.1.60) to set the lifetime?

_Thanks for the answers!_

**Comment by Mohamed-512** [comment]
No. I just removed the outdated example. But you can set the lifetime by using the same flag.
