### ISSUE TITLE
How to set multiple cookies

### ISSUE THREAD

**Issue by tunglambk** [Mohamed-512/Extra-Streamlit-Components#59]
I encountered a `streamlit.errors.DuplicateWidgetID` error, which seems to arise when attempting to set multiple cookies using the cookie manager. The error message indicates that there are multiple widgets with the same 'key' set. 

The error occurs in the following block of code:
```
st.session_state['cookie_manager'].set('user_token', access_token, expires_at=expires_at)
st.session_state['cookie_manager'].set('refesh_token', refresh_token, expires_at=expires_at)
```

![image](https://github.com/Mohamed-512/Extra-Streamlit-Components/assets/53996158/064f6b1f-9345-4db7-8442-bcd3d7117378)

Is there any way to set multiple cookies like this?

Thank you

**Comment by karunpoudel-chr** [comment]
You can provide different `key` parameter for those individual call.

**Comment by Mohamed-512** [comment]
@karunpoudel-chr suggestion is valid. If folks want a batch add method, then emote 👍 on this comment.

**Comment by Mohamed-512** [comment]
I have added a batch add method to the cookie manager. Please upgrade to 0.1.70+

**Comment by miukki** [comment]
where is documentation about batch add method
