### ISSUE TITLE
experimental_get_query_params deprecation

### ISSUE THREAD

**Issue by tristndeltaemerald** [Mohamed-512/Extra-Streamlit-Components#60]
Highlighting the warning that experimental_get_query_params() will be deprecated on 2024-04-11 and should be replaced with query_params

![Screenshot 2024-01-24 at 12 00 27 PM](https://github.com/Mohamed-512/Extra-Streamlit-Components/assets/119699444/3448c79f-9088-4a10-b4f4-1d3563f9619b)

Is it on the roadmap to support this transition?

**Comment by Mohamed-512** [comment]
resolved in a new commit. new version of the package to be published soon.
