### ISSUE TITLE
streamlit.errors.DuplicateWidgetID: There are multiple widgets with the same `key='set'`.

### ISSUE THREAD

**Issue by jump2cn** [Mohamed-512/Extra-Streamlit-Components#61]
hi team,
I get this error when I want to add the cookie.set code into a function. and sometime the error will report with other keys like 'init', 'get_all', and so on.

![demo test log](https://github.com/Mohamed-512/Extra-Streamlit-Components/assets/1173757/4c677f1d-54bd-4d59-b686-fcc6677e22fa)

even if I cache the cookie manager , it also gets warring and error
```python
import streamlit as st
import extra_streamlit_components as stx

@st.cache_resource(experimental_allow_widgets=True)
def get_manager():
    return stx.CookieManager()

def set_cookie():
    get_manager().set('key_test2', 'test2')
    
st.write("This is a test page.")

get_manager().set('key_test', 'test')

set_cookie()
st.write('set by function')
```

![demo log3](https://github.com/Mohamed-512/Extra-Streamlit-Components/assets/1173757/a60c7b42-fb26-48d6-8a60-42f424485e8d)

![图片](https://github.com/Mohamed-512/Extra-Streamlit-Components/assets/1173757/a45a6729-8f7c-4d92-8eb1-8cae3a9f27bb)

**Comment by E-delweiss** [comment]
Same problem here. 
FYI a quick fix may be to add key like : 

```python
cookie_manager.set("a","b", key=2)
cookie_manager.set("a","b", key=3)
```

I agree with you, it's not convenient hop there will be a fix.

**Comment by Mohamed-512** [comment]
Added batch set method in version 0.1.70
