### ISSUE TITLE
Extra vertical space when creating new cookie_manager

### ISSUE THREAD

**Issue by Takher** [Mohamed-512/Extra-Streamlit-Components#62]
When running this code

```python
import streamlit as st
import extra_streamlit_components as stx

st.write("# Cookie Manager Example")

@st.cache_resource(experimental_allow_widgets=True)
def get_manager():
    return stx.CookieManager()

st.write("Start get manager")
cookie_manager = get_manager()
st.write("done it")
```

I find that there is an extra vertical space:
<img width="917" alt="image" src="https://github.com/Mohamed-512/Extra-Streamlit-Components/assets/6210203/658c383d-177d-41eb-bb2b-92a562101302">

However, if I remove the `experimental_allow_widgets=True` option, I get this issue 

<img width="815" alt="image" src="https://github.com/Mohamed-512/Extra-Streamlit-Components/assets/6210203/cf65606f-25f1-4d24-b40b-733a397235c6">

Python 3.9.18
Streamlit, version 1.29.0
extra-streamlit-components 0.1.60

**Comment by hl5biw** [comment]
I also have same issue.

**Comment by NathanChen198** [comment]
I am having the same issue.

**Comment by lambda-science** [comment]
Same issue, please fix it's horrible

**Comment by lambda-science** [comment]
@Mohamed-512

**Comment by lambda-science** [comment]
@hl5biw @NathanChen198 @Takher Maybe you found a work-around ? :)
@Mohamed-512

**Comment by NathanChen198** [comment]
Manage to resolve it using css

def RemoveEmptyElementContainer():
    st.markdown(
        f""" 
            <style>
                .element-container:has(iframe[height="0"]) {{ display: none; }}
            </style>
        """, unsafe_allow_html=True
    )

**Comment by lambda-science** [comment]
> Manage to resolve it using css
> 
> ```python
> def RemoveEmptyElementContainer():
>     st.markdown(
>         f""" 
>             <style>
>                 .element-container:has(iframe[height="0"]) {{ display: none; }}
>             </style>
>         """, unsafe_allow_html=True
>     )
> ```

You just saved me, thank you very much !

**Comment by Mohamed-512** [comment]
Hey all, thanks for bringing it to my attention, and thanks @NathanChen198 for the fix. I have added it in a new version of the package `0.1.71`.
