### ISSUE TITLE
On Streamlit 1.0.0, unable to read cookies set in a previous session

### ISSUE THREAD

**Issue by isaiahstjohn** [Mohamed-512/Extra-Streamlit-Components#7]
The Streamlit version 1.0.0 update causes this issue to recur. There is no issue with Streamlit version 0.89.0. Previous issue: #5.

Here's a simple app to demonstrate the issue.

```python
import streamlit as st
import extra_streamlit_components as stx

st.write("Demo")
          
cookie_manager = stx.CookieManager()

def save_cookie():
    cookie_manager.set("c", "my-cookie")
    
c = cookie_manager.get("c")
st.write(c)
   
if not c:
    st.write('No cookie "c" found')
    st.button("Save cookie", on_click=save_cookie)
```

After clicking the button to set the cookie and then refreshing the page, the app is unable to load the cookie. Yet using the developer console, we can verify that the cookie is there.

**Comment by Mohamed-512** [comment]
I just confirmed this issue is not valid. If you open the developer console, do you see cookie manager when is the expiry of the added cookie, once you click save of course.

**Comment by Mohamed-512** [comment]
I get you point now. Well, it might not be technically a bug but this change of behaviour must have been because of underlying change in streamlit architecture. And either ways, it needs to work in 1.0.0 just as good as before, so I will try making an update today.
